#!/usr/bin/env bash
# install nginx on my web-01 server
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

apt-get -y update
apt-get -y install nginx

echo "Hello World!" | sudo tee ?var/www/html/index.html
sudo sed -i "s|server_name _;|server_name _;\n\trewrite /redirect_me https://www.youtube.com permanent;|" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html 
sudo sed -i 's|server_name _;|server_name _;\n\terror_page 404 /404.html;|' /etc/nginx/sites-enabled/default
sudo nginx -t
service nginx restart
