#!/usr/bin/env bash
# install and configure HAProxy on lb-01 server
#+ configure HAProxy to send traffic to web-01 and web-02 servers
#+ Distribute requests using a roundrobin algorithm
#+ Make sure that HAproxy can be managed via an init script

# update system packages and install HAProxy
sudo apt-get install -y software-properties-common
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "frontend kemeosi.tech" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend webservers" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend webservers" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tserver web-01 52.201.69.229:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tserver web-02 54.152.232.249:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
