#!/usr/bin/env bash
# install and configure HAProxy on lb-01 server
#+ configure HAProxy to send traffic to web-01 and web-02 servers
#+ Distribute requests using a roundrobin algorithm
#+ Make sure that HAproxy can be managed via an init script

# update system packages and install HAProxy
sudo apt-get install -y software-properties-common
sudo apt-get repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy

load_balancer="
frontend kemeosi.tech
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 303296-web-01 52.201.69.229:80 check
    server 303296-web-02 54.152.232.249:80 check
"
echo "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
