#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
#  localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8
# Before running the script:
# localhost resolves to 127.0.0.1
# facebook.com resolves to 31.13.66.35

# copies the content of the original /etc/hosts file to a new file named hosts.new in the user's home directory (~).
cp /etc/hosts ~/hosts.new

# uses the sed command to modify the hosts.new file replaces any line that starts with 127
# (which typically contains the localhost entry) with two new lines: 127.0.0.2 localhost and 8.8.8.8 facebook.com.
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# copies the modified hosts.new file back to the original /etc/hosts file, effectively updating the DNS configurations.
cp -f ~/hosts.new /etc/hosts
